# yaml-language-server: $schema=https://json.schemastore.org/eslintrc

ignorePatterns:
  - "**/dist"

overrides:
  - files: [ "*.ts", "*.tsx" ]
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/strict-type-checked
      - plugin:@typescript-eslint/stylistic-type-checked
      - plugin:jsdoc/recommended-typescript-error
      - plugin:prettier/recommended

    plugins:
      - import

    parserOptions:
      project: ./tsconfig.json

    rules:
      "prettier/prettier":
        - error
        - singleQuote: true
          semi: false

      # Prefer type imports/exports
      "@typescript-eslint/consistent-type-imports": error
      "@typescript-eslint/consistent-type-exports": error

      # Allow `${number}`
      "@typescript-eslint/restrict-template-expressions":
        - error
        - allowNumber: true

      # Only require jsdoc on exports
      "jsdoc/require-jsdoc":
        - error
        - publicOnly: true

      # Require a blank line between description and other tags
      "jsdoc/tag-lines":
        - error
        - any
        - startLines: 1

      # Alphabetically sort imports, and include a blank line between groups
      "import/order":
        - error
        - alphabetize:
            caseInsensitive: true
            order: asc
          newlines-between: always

      # Make sure imports are at the top of the file
      "import/first": error
